name: tongmoopa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  scoped_model: ^1.1.0
  image_picker: ^0.6.7+14
  google_maps_flutter: ^1.0.6
  location: ^3.0.2
  carousel_slider: ^2.3.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  cloud_firestore: ^0.14.1+2
  firebase_storage: ^4.0.1
  firebase_analytics: ^6.2.0
  firebase_crashlytics: ^0.2.3
  toast: ^0.1.5
  flutter_email_sender: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/theone.jpg"

flutter:

  uses-material-design: true

  assets:
    - images/
